### ISSUE TITLE
1.0.9 did not work for me

### ISSUE THREAD

**Issue by StephanJanosch** [mpicbg-scicomp/gtt#1]

**Comment by adomingues** [comment]
I am also having some issues with v1.0.9. After starting it is stuck on loading. I tried to filter by project / user and refresh but nothing happens (> 15 minutes loading).

**Comment by adomingues** [comment]
Forget about my issue. Adding an access token solved the issue.

**Comment by hkmoon** [comment]
Please, use 1.1.1 instead.
