### ISSUE TITLE
Refresh returns no data at random, with same fields returning data after repeated refresh

### ISSUE THREAD

**Issue by r0bbie** [mpicbg-scicomp/gtt#4]
On version v[1.1.3](https://github.com/mpicbg-scicomp/gtt/releases/tag/v1.1.3), AppImage build on Ubuntu

I've completed the configuration, input a project, and user, date, etc. On hitting "Refresh" no data is returned on most occasions, however if I continually hit "Refresh" after a few attempts data will then be correctly displayed.

**Comment by hkmoon** [comment]
Thanks a lot for the report and sorry for the late answer.
Actually, single repo reporting had an issue. [Version 1.1.4](https://github.com/mpicbg-scicomp/gtt/releases/tag/v1.1.4) fixed it.

**Comment by hkmoon** [comment]
There was electron-builder issue and it crash when it starts. This is fixed now.
